### ISSUE TITLE
При создании фирмы и обновлении фирмы недостаточно проверок

### ISSUE THREAD

**Issue by Maksimovich1** [Maksimovich2/application#4]
При создании или обновлении фирмы если передать строку которая не является телефоном то приложение дает нормально его сохранить
![image](https://user-images.githubusercontent.com/25402494/178150640-fcaaf3cd-535d-4b43-96bd-815048489bd7.png)
![image](https://user-images.githubusercontent.com/25402494/178150652-f68b163f-abd9-4122-a713-487068c7ef23.png)

**Comment by Maksimovich2** [comment]
Done.
Added validation of the phone number and validation of the company before saving
