### ISSUE TITLE
Сокрытие внутренних ИД

### ISSUE THREAD

**Issue by Maksimovich1** [Maksimovich2/application#5]
Сейчас мы наружу отдаем ид которое у нас в бд, это не совсем правильно. Нужно создать в таблицах новые поля с именем например uuid_d с типом данных UUID.
И его отдавать в качестве ключа вместо ИД
Из ДТО нужно убрать id 

Также переделать поиск и обновление по UUID

Добавить индекс в бд на это поле

**Comment by Maksimovich2** [comment]
Done.
