### ISSUE TITLE
Ошибка при обновлении заявки

### ISSUE THREAD

**Issue by Maksimovich1** [Maksimovich2/application#7]
Если отправить запрос
![image](https://user-images.githubusercontent.com/25402494/178150989-8490a24d-cfd7-4fce-8f8d-891ac32ebddb.png)

То вместо ошибки клиента я получу страшную 500-ю

![image](https://user-images.githubusercontent.com/25402494/178151006-f979e5c3-5573-4653-a807-30f86f80ab3e.png)
[logs.txt](https://github.com/Maksimovich2/application/files/9079332/logs.txt)

Лог во вложении

**Comment by Maksimovich2** [comment]
done.
